# используем язык java. Travis CI поддерживает и другие языки.
language: java
jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database dreamjob' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -youcanwriteme@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="e75242f2-495e-4946-b7ae-30a30da18156"